name: Build ZMK

on:
  workflow_dispatch:
  push:
    branches: [ initial-zmk-config ]
  pull_request:
    branches: [ initial-zmk-config ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: config

      - name: Checkout ZMK firmware
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Build (nice_nano_v2 + nice_nano_4x6)
        uses: zmkfirmware/zmk-build-action@v1
        with:
          zmk_path: zmk
          config_path: config/config
          board: nice_nano_v2
          shield: nice_nano_4x6

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: zmk/build/zephyr/*.uf2
